dist: trusty
language: node_js
sudo: required
node_js:
  - '8.2.0'
services:
  - docker
cache:
  directories:
  - node_modules
addons:
  hosts:
    - kafka
    - schema-registry
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libsasl2-dev libssl-dev
  - docker-compose up -d
